### ISSUE TITLE
绝对路径报错

### ISSUE THREAD

**Issue by Komugisama** [ChenjieXu/pyzxing#10]
您好，我想请教使用pyzxing进行开发时遇到的问题，使用绝对路径会报错/找不到文件，使用绝对路径则能正常识别，具体情况如下：

执行python scanner.py -f D:/pyzxing/images/codabar.png报错：
```
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at java.net.URL.<init>(Unknown Source)
        at com.google.zxing.client.j2se.ImageReader.readImage(ImageReader.java:44)
        at com.google.zxing.client.j2se.DecodeWorker.decode(DecodeWorker.java:125)
        at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:76)
```
执行python scanner.py -f file:///D:/pyzxing/images/codabar.png输出：File not found!
执行python scanner.py -f images/codabar.png则能正常识别

**Comment by ChenjieXu** [comment]
问题应该是windows下java绝对路径格式错误，请尝试D:\pyzxing\images\codabar.png或file:/D:/pyzxing/images/codabar.png。

**Comment by Komugisama** [comment]
尝试过了，似乎还是不太行，我修改了reader.py文件，将相对路径转为绝对路径后解决了该问题
