### ISSUE TITLE
Error in Python 3.9

### ISSUE THREAD

**Issue by vlsd** [ChenjieXu/pyzxing#12]
I'm getting an error when running the `scanner.py` script on the back of my ID card. Here's the traceback:

```
python scanner.py -f dl_back.jpg 
Use local jar file.
Traceback (most recent call last):
  File "/Users/vlsd/projects/my_project/scanner.py", line 27, in <module>
    main(args)
  File "/Users/vlsd/projects/my_project/scanner.py", line 13, in main
    results = reader.decode(args.file)
  File "/Users/vlsd/projects/my_project/.venv/lib/python3.9/site-packages/pyzxing/reader.py", line 45, in decode
    results = self._decode(filenames[0].replace('\\', '/'))
  File "/Users/vlsd/projects/my_project/.venv/lib/python3.9/site-packages/pyzxing/reader.py", line 61, in _decode
    result = [self._parse_single(
  File "/Users/vlsd/projects/my_project/.venv/lib/python3.9/site-packages/pyzxing/reader.py", line 61, in <listcomp>
    result = [self._parse_single(
  File "/Users/vlsd/projects/my_project/.venv/lib/python3.9/site-packages/pyzxing/reader.py", line 90, in _parse_single
    result['points'] = [ast.literal_eval(
  File "/Users/vlsd/projects/my_project/.venv/lib/python3.9/site-packages/pyzxing/reader.py", line 90, in <listcomp>
    result['points'] = [ast.literal_eval(
  File "/Users/vlsd/.pyenv/versions/3.9.0/lib/python3.9/ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "/Users/vlsd/.pyenv/versions/3.9.0/lib/python3.9/ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "/Users/vlsd/.pyenv/versions/3.9.0/lib/python3.9/ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "/Users/vlsd/.pyenv/versions/3.9.0/lib/python3.9/ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "/Users/vlsd/.pyenv/versions/3.9.0/lib/python3.9/ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: <ast.Name object at 0x109b54a00>
```

I wonder if Python 3.9 introduced some breaking changes to how `ast` behaves?

**Comment by vlsd** [comment]
Closing this since using the latest commit fixes the problem. It seems to only be an issue with the current PyPi release
