### ISSUE TITLE
Error when does not detect any barcode

### ISSUE THREAD

**Issue by Cristianasp** [ChenjieXu/pyzxing#14]
Hello ! Thank you for your work. 

I am testing your wrapper with some images and for a image with no barcode I got this error:

Traceback (most recent call last):
  File "pyzxing/scanner.py", line 27, in <module>
    main(args)
  File "pyzxing/scanner.py", line 16, in main
    results_string = [result['parsed'] for result in results]
  File "pyzxing/scanner.py", line 16, in <listcomp>
    results_string = [result['parsed'] for result in results]
KeyError: 'parsed'

**Comment by ChenjieXu** [comment]
Thank you！I will fix it
