### ISSUE TITLE
Decode doesn't work with spaces in the path

### ISSUE THREAD

**Issue by oscarbailey-tc** [ChenjieXu/pyzxing#23]
My code:
```
        codes = reader.decode(r"C:\\Users\\oscar\\Projects\\Camera Project\\captures\\barcode_Color.png")
```

The error message:
```
Exception in thread "main" java.util.concurrent.ExecutionException: javax.imageio.IIOException: Can't get input stream from URL!
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:96)
Caused by: javax.imageio.IIOException: Can't get input stream from URL!
        at javax.imageio.ImageIO.read(Unknown Source)
        at com.google.zxing.client.j2se.ImageReader.readImage(ImageReader.java:44)
        at com.google.zxing.client.j2se.DecodeWorker.decode(DecodeWorker.java:125)
        at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:76)
        at com.google.zxing.client.j2se.DecodeWorker.call(DecodeWorker.java:56)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: C:\Users\oscar\Projects\Camera (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at sun.net.www.protocol.file.FileURLConnection.connect(Unknown Source)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(Unknown Source)
        at java.net.URL.openStream(Unknown Source)
        ... 9 more
```

Specifically this line:
```
Caused by: java.io.FileNotFoundException: C:\Users\oscar\Projects\Camera (The system cannot find the file specified)
```

**Comment by ChenjieXu** [comment]
Please try codes = reader.decode(r"C:\\Users\\oscar\\Projects\\Camera\ Project\\captures\\barcode_Color.png")

**Comment by ChenjieXu** [comment]
If there are any updates, feel free to reopen this issue.
