### ISSUE TITLE
安装成功但测试运行失败

### ISSUE THREAD

**Issue by urnotlxr** [ChenjieXu/pyzxing#33]
``你好，我在按README.md安装pyzxing的时候遇到了一些问题。
首先是运行测试脚本
`python -m unittest tests.test_decode`
得到了如下结果: FAILED (failures=2, errors=6)
```
Exception in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
EException in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
EException in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
EException in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
FException in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
Exception in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
Exception in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
Exception in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
Exception in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
Exception in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
FException in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
E.Exception in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
EException in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
E
======================================================================
ERROR: test_codabar (tests.test_decode.TestBarCodeReaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/lappy/文档/cv-practice/ZXing/pyzxing/tests/test_decode.py", line 16, in test_codabar
    self.assertEqual(result[0]['parsed'], gt)
IndexError: list index out of range

======================================================================
ERROR: test_code128 (tests.test_decode.TestBarCodeReaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/lappy/文档/cv-practice/ZXing/pyzxing/tests/test_decode.py", line 30, in test_code128
    self.assertEqual(result[0]['parsed'], gt)
IndexError: list index out of range

======================================================================
ERROR: test_code39 (tests.test_decode.TestBarCodeReaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/lappy/文档/cv-practice/ZXing/pyzxing/tests/test_decode.py", line 23, in test_code39
    self.assertEqual(result[0]['parsed'], gt)
IndexError: list index out of range

======================================================================
ERROR: test_nobarcodefile (tests.test_decode.TestBarCodeReaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/lappy/文档/cv-practice/ZXing/pyzxing/tests/test_decode.py", line 59, in test_nobarcodefile
    self.assertEqual(result[0].get('parsed', None), None)
IndexError: list index out of range

======================================================================
ERROR: test_pdf417 (tests.test_decode.TestBarCodeReaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/lappy/文档/cv-practice/ZXing/pyzxing/tests/test_decode.py", line 37, in test_pdf417
    self.assertEqual(result[0]['parsed'], gt)
IndexError: list index out of range

======================================================================
ERROR: test_qrcode (tests.test_decode.TestBarCodeReaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/lappy/文档/cv-practice/ZXing/pyzxing/tests/test_decode.py", line 44, in test_qrcode
    self.assertEqual(result[0]['parsed'], gt)
IndexError: list index out of range

======================================================================
FAIL: test_multibarcodes (tests.test_decode.TestBarCodeReaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/lappy/文档/cv-practice/ZXing/pyzxing/tests/test_decode.py", line 69, in test_multibarcodes
    self.assertEqual(set(result_string), set(gt))
AssertionError: Items in the second set but not the first:
b'201541368446'
b'201541371885'
b'201541332863'
b'201541332768'
b'201541395223'
b'201541350294'
b'201541393029'

======================================================================
FAIL: test_multifiles (tests.test_decode.TestBarCodeReaderDecode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/media/lappy/文档/cv-practice/ZXing/pyzxing/tests/test_decode.py", line 86, in test_multifiles
    self.assertEqual(set(results_string), set(gt))
AssertionError: Items in the second set but not the first:
b'31117013206375'
b'[)>\x1e01\x1d96123450000\x1d222\x1d111\x1dMODE2'
b'-ActiveBarcode-ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-ActiveBarcode-ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-ActiveBarcode-ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-ActiveBarcode-ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-ActiveBarcode-ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-ActiveBarcode-ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890'
b'When we at WRT talk about \\"text,\\" we are generally talking about a particular kind of readable information encoding - and readable is a complex proposition. Text may be stylized in a way we are unfamiliar with, as in blackletter - it may be interspersed with some markup we don\\\'t understand, such as HTML - it may be be a substitution system we aren\\\'t familiar with, such as braille or morse code - or it may be a system that, while technically human-readable, isn\\\'t particularly optimized for reading by humans, as with barcodes (although barcodes can be read).'
b'TEST-SHEET'
b'8101054321120021123456'

----------------------------------------------------------------------
Ran 9 tests in 5.651s

FAILED (failures=2, errors=6)

```
之后我运行了如下指令
```

git submodule init
git submodule update
cd zxing
mvn install -DskipTests

```
得到输出
```

……

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ZXing 3.4.1-SNAPSHOT:
[INFO] 
[INFO] ZXing .............................................. SUCCESS [ 21.216 s]
[INFO] ZXing Core ......................................... SUCCESS [ 43.372 s]
[INFO] ZXing Java SE extensions ........................... FAILURE [  4.195 s]
[INFO] ZXing zxing.org web app ............................ SKIPPED
[INFO] ZXing Appspot-based encoder ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:09 min
[INFO] Finished at: 2022-03-02T16:20:19+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.13:check (default) on project javase: Too many files with unapproved license: 1 See RAT report in: /media/lappy/文档/cv-practice/ZXing/pyzxing/zxing/javase/target/rat.txt -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :javase


```
再接着运行
```

cd javase
mvn -DskipTests package assembly:single

```
得到输出
```
……

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.526 s
[INFO] Finished at: 2022-03-02T16:21:33+08:00
[INFO] ------------------------------------------------------------------------

```
运行示例代码，报错
```

Exception in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)
[]


```
我对没有了解过Java和maven，请问我该如何解决遇到的问题？

**Comment by ChenjieXu** [comment]
您好，和您确认下您的运行环境和软件版本，您使用的是否是Linux系统，使用的是哪个版本的pyzxing程序？
我看您是通过build得到的jar包，在zxing/javase/target目录下是否有jar文件？
如果找到了请运行java -jar “jar文件地址” “需要识别的图片地址”，并将打印出的信息反馈给我。

**Comment by QLW-07** [comment]
你好，我使用的Linux系统，编译得到的pyzxing版本是1.0.2b0

bulid得到的jar包，运行如下：
(pyzxing) xt@xt:~/pyzxing/zxing$ java -jar ./javase/target/javase-3.4.1-SNAPSHOT.jar 1.jpg
./javase/target/javase-3.4.1-SNAPSHOT.jar中没有主清单属性
(pyzxing) xt@xt:~/pyzxing/zxing$ java -jar ./javase/target/gwt-user-2.8.2.jar 1.jpg
Error: Invalid or corrupt jarfile ./javase/target/gwt-user-2.8.2.jar
(pyzxing) xt@xt:~/pyzxing/zxing$ java -jar ./javase/target/javase-3.4.1-SNAPSHOT-javadoc.jar 1.jpg
./javase/target/javase-3.4.1-SNAPSHOT-javadoc.jar中没有主清单属性
(pyzxing) xt@xt:~/pyzxing/zxing$ java -jar ./javase/target/javase-3.4.1-SNAPSHOT-sources.jar 1.jpg
./javase/target/javase-3.4.1-SNAPSHOT-sources.jar中没有主清单属性


运行脚本后报错提示依然情况如下：
Exception in thread "main" java.lang.IllegalArgumentException: Bad escape
	at sun.nio.fs.UnixUriUtils.fromUri(UnixUriUtils.java:87)
	at sun.nio.fs.UnixFileSystemProvider.getPath(UnixFileSystemProvider.java:98)
	at java.nio.file.Paths.get(Paths.java:138)
	at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
	at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)

**Comment by IllBthere4U** [comment]
>您好，请问您解决了么？我也遇到了相同的状况。

**Comment by ChenjieXu** [comment]
您好！看起来您遇到了复杂的安装和构建问题。让我帮您解决这个问题。

## 问题分析

从您的错误信息来看，主要有两个问题：

1. **JAR文件构建问题**：Maven构建的JAR文件没有正确的主清单属性
2. **路径转义问题**：ZXing在处理文件路径时出现"Bad escape"错误

## 解决方案

### 1. 重新构建正确的JAR文件

请尝试以下步骤：

```bash
# 1. 清理之前的构建
cd zxing
mvn clean

# 2. 重新构建，跳过RAT检查
mvn install -DskipTests -Drat.skip=true

# 3. 构建可执行的JAR文件
cd javase
mvn package -DskipTests -Drat.skip=true assembly:single
```

### 2. 验证JAR文件

构建完成后，检查生成的文件：
```bash
ls -la target/
```

您应该看到一个类似 `javase-3.4.1-SNAPSHOT-jar-with-dependencies.jar` 的文件。

### 3. 测试JAR文件

```bash
java -jar target/javase-*-jar-with-dependencies.jar --help
```

### 4. 如果构建仍然失败

如果Maven构建继续失败，可以尝试：

```bash
# 使用预编译的JAR文件
cd ..
python -c "from pyzxing import BarCodeReader; reader = BarCodeReader()"
```

pyzxing会自动从GitHub releases下载预编译的JAR文件。

### 5. 手动下载JAR文件

如果自动下载失败，可以手动下载：

```bash
# 创建缓存目录
mkdir -p ~/.local

# 下载预编译JAR文件
wget https://github.com/ChenjieXu/pyzxing/releases/download/v0.1/javase-3.4.1-SNAPSHOT-jar-with-dependencies.jar -O ~/.local/javase-3.4.1-SNAPSHOT-jar-with-dependencies.jar
```

## 环境要求

确保您安装了：
- Java 8或更高版本
- Maven 3.x
- Python 3.7+

## 验证安装

安装完成后，运行以下测试：

```python
from pyzxing import BarCodeReader
reader = BarCodeReader()
print("pyzxing安装成功！")
```

如果以上步骤都无法解决问题，请提供：
1. 您的Java版本：`java -version`
2. 您的Maven版本：`mvn -version`
3. 完整的错误日志

我会继续帮您解决问题。

**Comment by ChenjieXu** [comment]
已在 [pyzxing v1.2.0](https://github.com/ChenjieXu/pyzxing/releases/tag/v1.2.0) 中修复并加入回归测试。

v1.2.0 使用新的 pyzxing Runner，并正确构造输入 URI；包含 Unicode、空格、`%` 和 `#` 的目录及文件名都已用真实二维码验证，不再触发这里的 `Bad escape`。正常安装 v1.2.0 会使用随发布提供并校验的 Runner，无需用户自行编译 ZXing/Maven JAR。

因此关闭此 issue。如升级后仍有不同的安装或路径问题，请另开 issue，并附操作系统、Python/Java 版本和最小可复现路径。
