### ISSUE TITLE
reader.decode fails for a certain QR code

### ISSUE THREAD

**Issue by arihans** [ChenjieXu/pyzxing#6]
For this spicific [QR_CODE](https://pasteboard.co/JvlCK83.png) reader.decode() fails with error :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arion/.local/lib/python3.8/site-packages/pyzxing/reader.py", line 45, in decode
    results = self._decode(filenames[0].replace('\\', '/'))
  File "/home/arion/.local/lib/python3.8/site-packages/pyzxing/reader.py", line 61, in _decode
    result = [self._parse_single(
  File "/home/arion/.local/lib/python3.8/site-packages/pyzxing/reader.py", line 61, in <listcomp>
    result = [self._parse_single(
  File "/home/arion/.local/lib/python3.8/site-packages/pyzxing/reader.py", line 90, in _parse_single
    result['points'] = [ast.literal_eval(
  File "/home/arion/.local/lib/python3.8/site-packages/pyzxing/reader.py", line 90, in <listcomp>
    result['points'] = [ast.literal_eval(
  File "/usr/lib/python3.8/ast.py", line 59, in literal_eval
    if isinstance(node_or_string, Expression):
  File "/usr/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags, _feature_version=feature_version)
  File "<unknown>", line 1
    param1):
          ^
SyntaxError: unmatched ')'
```
<img src="https://user-images.githubusercontent.com/39364391/95785619-b77de700-0cf3-11eb-862f-8261dd824416.png" width="50%">

Here's my code - 
```
>>> from pyzxing import BarCodeReader
>>> reader = BarCodeReader()
Use local jar file.
>>> reader.decode('8RXzm7LJ.png')

/* Errors */
```

Here's the decoded output, decoded in the xzing website - 
```
param0 = "2XEY1jQ1gZv8f03Y8juNiXOHgXTymJtO"
param1 = "XRrI4mjQvdrfCRPsleVI2jK7ySHp1EXa"
param2 = 690
output = ""
o = False
i = 0
for c0, c1 in zip(param0, param1):
  if i % 2 == 0:
    cc = c0 + c1
    if cc.isnumeric() and o is False:
      o = True
      meh = param0 + str(param2) + param1
      for j in range(0, i * param2):
        x = 13
        if j % 2 == 0:
          x = 77
        output += meh[(j + x) % len(meh)]
        output = output[::-1]
    else:
      output += cc
      output = output[::-1]
  else:
    if ord(c0) == ord(c1):
      output += c1 + c0
    elif ord(c0) > ord(c1):
      output += c0
    else:
      output += c1
  i += 1
output = output[0:32]
print(output)
```

It works in the xzing website. and pyzxing works fine for the other 10 or so QR_CODEs I've tested it for.

---

- Python version : 3.8.6

**Comment by ChenjieXu** [comment]
I think pyzxing worked in decoding, but failed in parsing into structured output. I'll fix it.

**Comment by ChenjieXu** [comment]
It is fixed
