### ISSUE TITLE
URI is not hierarchical

### ISSUE THREAD

**Issue by Michelangelo-Y** [ChenjieXu/pyzxing#7]
1.run in python get errot result:
Use local jar file.
'java' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
2.use CMD:C:\Users\XXX>java -jar C:\\Users\\XXX\\.local\\javase-3.4.1-SNAPSHOT-jar-with-dependencies.jar C:\\Users\\XXX\\.local\\test\\*.png:
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
        at java.base/sun.nio.fs.WindowsUriSupport.fromUri(WindowsUriSupport.java:122)
        at java.base/sun.nio.fs.WindowsFileSystemProvider.getPath(WindowsFileSystemProvider.java:97)
        at java.base/java.nio.file.Path.of(Path.java:203)
        at java.base/java.nio.file.Paths.get(Paths.java:98)
        at com.google.zxing.client.j2se.CommandLineRunner.expand(CommandLineRunner.java:112)
        at com.google.zxing.client.j2se.CommandLineRunner.main(CommandLineRunner.java:76)

**Comment by ChenjieXu** [comment]
The python error does not show properly. Have you installed java on your PC?

**Comment by ChenjieXu** [comment]
Please let me know if there still have problems.
